const VERSION = '5.0.0';
const BUILD = '2026-09-08';
const STORAGE_KEY = 'explorActionV5';
const DEFAULT_PIN = '2468';
const PUBLIC_KEY_JWK = {"kty":"EC","crv":"P-256","x":"1E21DtgBiits5iniVnbYvVxkS1BoL9F8DDhZ7gK-QpA","y":"jcT_rbnoMwxrV5QVMsie5D697z2VPhmahSSWxQRpfGA","ext":true,"key_ops":["verify"]};
const FIRE_RISK_URL = 'https://www.risque-prevention-incendie.fr/pyrenees-orientales/';
const ASSETS = {
  guard:'assets/guide-guard.webp', point:'assets/guide-point.webp', think:'assets/guide-think.webp',
  welcome:'assets/guide-welcome.webp', adventure:'assets/guide-adventure.webp', calm:'assets/guide-calm.webp',
  logo:'assets/logo-clean.webp', logoPremium:'assets/logo-premium.webp'
};
const MISSION_GUIDE = {maillol:'welcome', vignes:'calm', art:'point', nature:'adventure'};
const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const app = $('#app');
let state = loadState();
let currentMission = null;
let currentStep = 0;
let timer = null;
let installPrompt = null;
let geoWatch = null;
let heading = null;
let currentBearing = null;
let leafletMap = null;
let leafletPlayer = null;
let photoObjectUrls = [];

function defaultState(){
  return {
    access:null,
    progress:{},
    adminPin:DEFAULT_PIN,
    organizerTest:false,
    team:{name:'', players:1, names:''},
    settings:{public:'ado', routeFilter:'all', sound:true, language:'fr', a11y:{largeText:false, highContrast:false, reduceMotion:false, autoSpeak:false}},
    version:VERSION
  };
}
function loadState(){
  let s = null;
  try{s = JSON.parse(localStorage.getItem(STORAGE_KEY)||'null')}catch{}
  if(!s){
    try{s = JSON.parse(localStorage.getItem('explorActionV4')||'null')}catch{}
  }
  if(!s){
    try{s = JSON.parse(localStorage.getItem('fafaState')||'null')}catch{}
  }
  const d = defaultState();
  s = {...d, ...(s||{})};
  s.settings = {...d.settings, ...(s.settings||{})};
  s.settings.a11y = {...d.settings.a11y, ...(s.settings.a11y||{})};
  s.team = {...d.team, ...(s.team||{})};
  s.progress ||= {};
  s.adminPin ||= DEFAULT_PIN;
  s.organizerTest = false; // never persist an unlocked organizer session across reloads
  s.version = VERSION;
  return s;
}
function save(){
  state.version = VERSION;
  localStorage.setItem(STORAGE_KEY, JSON.stringify(state));
  localStorage.removeItem('explorActionV4');
  localStorage.removeItem('fafaState');
}
function norm(s){return (s||'').toString().normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[’']/g,' ').replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim()}
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(t){const x=$('#toast');if(!x)return;x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2400)}
function haptic(pattern=30){try{navigator.vibrate?.(pattern)}catch{}}
function chime(ok=true){if(!state.settings.sound)return;try{const A=window.AudioContext||window.webkitAudioContext,a=new A(),o=a.createOscillator(),g=a.createGain();o.frequency.value=ok?660:180;g.gain.setValueAtTime(.07,a.currentTime);g.gain.exponentialRampToValueAtTime(.001,a.currentTime+.22);o.connect(g);g.connect(a.destination);o.start();o.stop(a.currentTime+.24)}catch{}}
function speak(text){if(!state.settings.sound)return toast('Audio désactivé');if(!('speechSynthesis' in window))return toast('Lecture vocale indisponible');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=state.settings.language==='ca'?'ca-ES':state.settings.language==='en'?'en-GB':'fr-FR';u.rate=.96;speechSynthesis.speak(u)}
function logoHTML(premium=false,cls='brand-logo'){return `<img class="${cls}" src="${premium?ASSETS.logoPremium:ASSETS.logo}" alt="Logo FAFATRAINING">`}
function guideHTML(pose,title,text,extra=''){return `<aside class="guide-card"><div class="guide-visual"><img src="${ASSETS[pose]||ASSETS.welcome}" alt="FAFA, guide Explor’Action"></div><div class="guide-copy"><span class="guide-label">FAFA te guide</span><h3>${title}</h3><p>${text}</p>${extra}</div></aside>`}
function formatMs(ms){const sec=Math.max(0,Math.floor(ms/1000)),h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60),s=sec%60;return h?`${h}h ${String(m).padStart(2,'0')}m`:`${m}m ${String(s).padStart(2,'0')}s`}
function pct(m,p){return Math.min(100,Math.round((p.done.length/Math.max(1,m.steps.length))*100))}
function missionMaxScore(m){const r=scoreRules();return m.steps.length*r.success+r.final}
function prog(m){
  if(!state.progress[m.id])state.progress[m.id]={done:[],score:0,hints:0,errors:0,tokens:[],elapsedMs:0,runningSince:null,paused:true,reached:[],skipped:[],finalDone:false,started:false,legacyPhotos:{}};
  const p=state.progress[m.id];
  p.done||=[];p.tokens||=[];p.reached||=[];p.skipped||=[];p.elapsedMs||=0;p.paused??=true;p.finalDone??=false;p.legacyPhotos||={};
  // V4 photo migration staging: do not save data URLs back into localStorage.
  if(p.photos && Object.keys(p.photos).length){p.legacyPhotos={...p.legacyPhotos,...p.photos};delete p.photos;setTimeout(()=>migrateLegacyPhotos(m.id),0)}
  return p;
}
function liveElapsed(p){return (p.elapsedMs||0)+(p.runningSince?Date.now()-p.runningSince:0)}
function startClock(p){if(!p.runningSince){p.runningSince=Date.now();p.paused=false;p.started=true;save()}}
function pauseClock(p){if(p.runningSince){p.elapsedMs=(p.elapsedMs||0)+(Date.now()-p.runningSince);p.runningSince=null}p.paused=true;save()}
function resumeClock(p){p.runningSince=Date.now();p.paused=false;p.started=true;save()}
function dist(a,b,c,d){const R=6371,x=(c-a)*Math.PI/180,y=(d-b)*Math.PI/180,z=Math.sin(x/2)**2+Math.cos(a*Math.PI/180)*Math.cos(c*Math.PI/180)*Math.sin(y/2)**2;return 2*R*Math.asin(Math.sqrt(z))}
function bearing(a,b,c,d){const p1=a*Math.PI/180,p2=c*Math.PI/180,dl=(d-b)*Math.PI/180;let y=Math.sin(dl)*Math.cos(p2),x=Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(dl);return (Math.atan2(y,x)*180/Math.PI+360)%360}
function cardinal(deg){return ['N','NE','E','SE','S','SO','O','NO'][Math.round(deg/45)%8]}
function effectiveRadius(s){const audience=state.settings.public;return Math.round(s.radius*(audience==='enfant'?1.35:audience==='adulte'?0.95:1))}
function scoreRules(){return state.settings.public==='enfant'?{success:80,hint:10,error:5,skip:40,final:180}:state.settings.public==='adulte'?{success:110,hint:30,error:12,skip:80,final:300}:{success:100,hint:20,error:10,skip:65,final:250}}
function firstLetter(s){return norm(s.answers?.[0]||'').charAt(0).toUpperCase()}
function publicTip(){return state.settings.public==='enfant'?'Lis doucement, observe autour de toi et joue avec ton équipe.':state.settings.public==='adulte'?'La réponse doit venir du lieu réel : cherche le détail patrimonial ou naturel avant de répondre.':'Observe, échange avec ton équipe et garde les yeux sur le terrain.'}
function questionText(s){if(state.settings.public==='enfant')return `${s.q} Petit coup de pouce : la réponse commence par « ${firstLetter(s)} ».`;if(state.settings.public==='adulte'&&s.expertBonus)return `${s.q} ${s.expertBonus}`;return s.q}
function factText(s){return state.settings.public==='enfant'?`À retenir : ${s.fact}`:s.fact}
function routeLevelClass(level){return `route-${level||'unknown'}`}
function routeMetric(value,suffix=''){return value==null?'À valider':`${value}${suffix}`}
function etrLabel(n){if(n==null)return 'À coter terrain';return ['','Très faible','Faible','Modéré','Élevé','Très élevé'][Math.max(1,Math.min(5,+n||1))]}
function applyAccessibility(){const a=state.settings.a11y;document.body.classList.toggle('a11y-large',!!a.largeText);document.body.classList.toggle('a11y-contrast',!!a.highContrast);document.body.classList.toggle('a11y-reduce',!!a.reduceMotion)}
function stopLive(){if(geoWatch!==null&&navigator.geolocation){navigator.geolocation.clearWatch(geoWatch);geoWatch=null}window.removeEventListener('deviceorientationabsolute',onOrientation);window.removeEventListener('deviceorientation',onOrientation);heading=null;currentBearing=null;if(leafletMap){try{leafletMap.remove()}catch{}leafletMap=null;leafletPlayer=null}photoObjectUrls.forEach(u=>URL.revokeObjectURL(u));photoObjectUrls=[]}

// Signed access codes (ECDSA P-256). The private key is never present in the GitHub package.
function b64uToBytes(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';return Uint8Array.from(atob(s),c=>c.charCodeAt(0))}
function bytesToText(b){return new TextDecoder().decode(b)}
async function verifyCode(code){
  try{
    const p=(code||'').trim().split('.');
    if(p.length!==3||p[0]!=='FAFA5')return null;
    const payloadBytes=b64uToBytes(p[1]);
    const payload=JSON.parse(bytesToText(payloadBytes));
    if(payload.v!==5||!payload.exp||Date.now()>payload.exp)return null;
    if(payload.scope!=='all'&&!MISSIONS.some(m=>m.id===payload.scope))return null;
    const key=await crypto.subtle.importKey('jwk',PUBLIC_KEY_JWK,{name:'ECDSA',namedCurve:'P-256'},false,['verify']);
    const ok=await crypto.subtle.verify({name:'ECDSA',hash:'SHA-256'},key,b64uToBytes(p[2]),payloadBytes);
    return ok?{exp:payload.exp,scope:payload.scope||'all'}:null;
  }catch{return null}
}
function accessValid(){return state.organizerTest||!!(state.access&&Date.now()<state.access.exp)}
function allowed(m){return state.organizerTest||!!state.access&&(state.access.scope==='all'||state.access.scope===m.id)}

// IndexedDB photos
function photoDB(){return new Promise((resolve,reject)=>{const r=indexedDB.open('ExplorActionV5Media',1);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains('photos'))db.createObjectStore('photos',{keyPath:'id'})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function photoPut(mid,i,blob){const db=await photoDB();return new Promise((resolve,reject)=>{const tx=db.transaction('photos','readwrite');tx.objectStore('photos').put({id:`${mid}:${i}`,mission:mid,step:i,blob,updated:Date.now()});tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
async function photoList(mid){const db=await photoDB();return new Promise((resolve,reject)=>{const r=db.transaction('photos').objectStore('photos').getAll();r.onsuccess=()=>resolve(r.result.filter(x=>x.mission===mid).sort((a,b)=>a.step-b.step));r.onerror=()=>reject(r.error)})}
async function photoClear(){try{const db=await photoDB();await new Promise((resolve,reject)=>{const tx=db.transaction('photos','readwrite');tx.objectStore('photos').clear();tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)})}catch{}}
async function dataUrlToBlob(dataUrl){const r=await fetch(dataUrl);return r.blob()}
async function migrateLegacyPhotos(mid){const m=MISSIONS.find(x=>x.id===mid);if(!m)return;const p=prog(m);const entries=Object.entries(p.legacyPhotos||{});if(!entries.length)return;for(const [i,src] of entries){try{await photoPut(mid,+i,await dataUrlToBlob(src))}catch{}}p.legacyPhotos={};save()}
async function savePhoto(mid,i,file){
  if(!file)return;
  const img=new Image(),url=URL.createObjectURL(file);
  img.onload=()=>{const c=document.createElement('canvas'),max=1280,scale=Math.min(1,max/img.width);c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);c.toBlob(async blob=>{try{await photoPut(mid,i,blob);$('#photoStatus').innerHTML='<span class="good">Photo enregistrée dans IndexedDB ✓</span>'}catch{toast('Impossible d’enregistrer la photo')}URL.revokeObjectURL(url)},'image/jpeg',.72)};
  img.onerror=()=>URL.revokeObjectURL(url);img.src=url;
}

function renderAccess(){
  stopLive();clearInterval(timer);applyAccessibility();
  app.innerHTML=`<main class="shell access access-wide"><section class="access-brand">${logoHTML(false,'access-logo')}<div><div class="eyebrow">FAFATRAINING</div><h1 class="title">Explor’Action</h1><p class="subtitle">Randonnée • patrimoine • GPS • énigmes • aventure grandeur nature</p></div></section><div class="access-grid"><section class="card hero access-panel"><span class="pill">🔐 Accès signé V5</span><h2>Entre dans l’aventure</h2><p class="subtitle">Saisis le code transmis par l’organisateur. Les codes V5 sont vérifiés par signature numérique et ne contiennent aucun secret de génération dans l’application publique.</p><label>Code d’accès</label><textarea id="accessCode" class="input code-input" rows="3" autocomplete="one-time-code" placeholder="FAFA5.…"></textarea><div class="row" style="margin-top:14px"><button class="btn" id="enter">Commencer</button><button class="btn secondary" id="admin">Administration</button></div><div class="offline-status">📲 PWA GitHub Pages • progression locale • photos IndexedDB • mode hors connexion après premier chargement</div></section>${guideHTML('point','Prêt à explorer ?','Le téléphone guide l’aventure, mais le terrain reste prioritaire. Regarde devant toi, respecte les sentiers et vérifie toujours les conditions du jour.')}</div></main>`;
  $('#enter').onclick=async()=>{const b=$('#enter');b.disabled=true;b.textContent='Vérification…';const v=await verifyCode($('#accessCode').value);b.disabled=false;b.textContent='Commencer';if(!v)return toast('Code invalide, altéré ou expiré');state.access=v;save();haptic([30,50,30]);renderHome()};
  $('#admin').onclick=adminLogin;
}
function adminLogin(){const pin=prompt('PIN administrateur');if(pin!==state.adminPin)return toast('PIN incorrect');renderAdmin()}
function renderAdmin(){
  stopLive();clearInterval(timer);applyAccessibility();
  app.innerHTML=`<main class="shell"><button class="btn secondary back" id="back">← Retour</button><div class="top">${logoHTML(true,'brand')}<div><div class="eyebrow">Administration locale</div><h1 class="title">Explor’Action V${VERSION}</h1></div></div>${guideHTML('guard','Pilotage terrain','Le générateur de codes est désormais séparé de l’application publique. Cette page sert au test, à l’audit et à la préparation terrain.')}<div class="grid" style="margin-top:16px"><section class="card"><h2>🧪 Mode Test organisateur</h2><p>Déverrouille toutes les missions et permet de tester une étape sans être dans la zone GPS. Aucun résultat obtenu dans ce mode ne doit être considéré comme un score joueur officiel.</p><button class="btn ${state.organizerTest?'danger':'secondary'}" id="testMode">${state.organizerTest?'Désactiver le mode Test':'Activer le mode Test'}</button></section><section class="card"><h2>🔐 Codes d’accès</h2><p class="small">La V5 utilise une signature asymétrique ECDSA P-256. La clé privée est conservée dans le paquet administrateur hors ligne et ne doit jamais être envoyée sur GitHub.</p><div class="warning">Le dépôt public ne contient que la clé publique de vérification.</div></section><section class="card"><h2>Sécurité locale</h2><p class="small">PIN initial : 2468. Change-le sur chaque appareil organisateur avant usage.</p><label>Nouveau PIN</label><input class="input" id="newpin" type="password"><button class="btn secondary" id="pinbtn">Changer le PIN</button></section></div><h2 class="section-title">Contrôle terrain</h2><div class="grid"><section class="card"><h3>Solutions</h3><button class="btn gold" id="solutions">Réponses & finals</button></section><section class="card"><h3>Données & sources</h3><button class="btn secondary" id="audit">Audit des étapes</button></section><section class="card"><h3>Recherche territoires</h3><button class="btn secondary" id="research">Références des 11 territoires</button></section><section class="card"><h3>Réinitialiser cet appareil</h3><button class="btn danger" id="reset">Effacer progression + photos</button></section></div></main>`;
  $('#back').onclick=()=>accessValid()?renderHome():renderAccess();
  $('#testMode').onclick=()=>{state.organizerTest=!state.organizerTest;save();renderAdmin()};
  $('#pinbtn').onclick=()=>{const p=$('#newpin').value.trim();if(p.length<4)return toast('4 caractères minimum');state.adminPin=p;save();toast('PIN modifié')};
  $('#solutions').onclick=renderSolutions;$('#audit').onclick=renderDataAudit;$('#research').onclick=renderAllTerritoryResearch;
  $('#reset').onclick=async()=>{if(confirm('Effacer progression, accès, profil équipe et photos de cet appareil ?')){state=defaultState();save();await photoClear();renderAccess()}};
}
function renderSolutions(){app.innerHTML=`<main class="shell"><button class="btn secondary back" id="back">← Admin</button><h1>Solutions maître du jeu</h1>${MISSIONS.map(m=>`<section class="card" style="margin:14px 0"><h2>${m.icon} ${m.title}</h2>${m.steps.map((s,i)=>`<details class="solution"><summary>${i+1}. ${s.name}</summary><p class="small">${s.q}<br><b>Réponse :</b> ${s.answers[0]} • <b>Fragment :</b> ${s.token}<br><b>Zone GPS :</b> ${s.radius} m • <b>Confiance :</b> ${s.gpsConfidence}</p></details>`).join('')}<p><b>Final :</b> ${m.final}</p></section>`).join('')}</main>`;$('#back').onclick=renderAdmin}
function renderDataAudit(){app.innerHTML=`<main class="shell"><button class="btn secondary back" id="back">← Admin</button><h1>Audit données terrain</h1><p class="subtitle">Revue documentaire : ${BUILD}. Une source officielle ne remplace jamais une reconnaissance GNSS sur le point exact du jeu.</p>${MISSIONS.map(m=>`<section class="card audit-card"><h2>${m.icon} ${m.title} • ${m.steps.length} étapes</h2><p><b>Statut métriques :</b> ${m.route.metricsStatus}</p>${m.steps.map((s,i)=>`<details><summary>${i+1}. ${s.name} — ${s.gpsConfidence}</summary><p><b>GPS :</b> ${s.lat}, ${s.lng} • rayon ${s.radius} m</p><p><b>Accès :</b> ${s.access}</p><p><b>Saisonnalité :</b> ${s.season}</p><p><a href="${s.source}" target="_blank" rel="noopener">Source documentaire ↗</a></p></details>`).join('')}</section>`).join('')}</main>`;$('#back').onclick=renderAdmin}

function renderHome(){
  stopLive();clearInterval(timer);applyAccessibility();if(!accessValid())return renderAccess();
  const available=MISSIONS.filter(allowed);
  const filtered=available.filter(m=>state.settings.routeFilter==='all'||m.route.level===state.settings.routeFilter);
  app.innerHTML=`<main class="shell">${state.organizerTest?'<div class="test-banner">🧪 MODE TEST ORGANISATEUR — GPS contournable • scores non officiels</div>':''}<header class="topbar">${logoHTML()}<div class="top-actions"><span class="pill timer" id="expiry"></span><button class="icon-btn" id="adminTop" title="Administration">⚙️</button></div></header><section class="card hero explor-hero"><div><div class="eyebrow">FAFATRAINING • AVENTURE OUTDOOR</div><h1>Explor’Action</h1><p class="subtitle">Un mélange de randonnée réelle, découverte patrimoniale, orientation GPS et jeu de terrain. Banyuls-sur-Mer est le territoire actuellement jouable ; les autres sont documentés mais restent volontairement verrouillés jusqu’à validation terrain.</p><div class="hero-actions"><button class="btn" id="startHome">🚀 Commencer l’aventure</button><button class="btn secondary" id="scores">🏆 Mes scores</button></div><div class="info-chips"><span class="pill">🧭 11 territoires</span><span class="pill">🥾 3 niveaux physiques</span><span class="pill">📍 ${available.length} mission${available.length>1?'s':''} autorisée${available.length>1?'s':''}</span></div><div class="home-tools"><button class="tool-btn" id="audio">${state.settings.sound?'🔊 Audio activé':'🔇 Audio coupé'}</button><button class="tool-btn" id="mapAll">🗺️ Carte territoire</button><button class="tool-btn" id="guide">❓ Guide FAFA</button><button class="tool-btn" id="installApp">📲 Installer</button></div></div><img class="hero-avatar" src="${ASSETS.point}" alt="FAFA"></section>
  <section class="flow-card"><div class="flow-title"><b>3 étapes pour partir</b><small>Territoire → profil → aventure</small></div><div class="flow-steps"><button data-go="territories"><span>1</span><b>Choisis ton territoire</b><small>Disponibilité et références réelles</small></button><button data-go="settings"><span>2</span><b>Prépare ton équipe</b><small>Public, équipe, accessibilité</small></button><button data-go="launch"><span>3</span><b>Choisis ton effort</b><small>Distance, D+, terrain, durée</small></button></div></section>
  <section id="territories" class="section-block"><div class="section-head"><div><div class="eyebrow">ÉTAPE 1</div><h2>Territoires</h2></div><p class="small">« Bientôt » signifie : recherches réelles en cours, mais aucun faux parcours GPS n’est proposé.</p></div><div class="village-strip">${TERRITORIES.map(v=>`<button class="village-card ${v.status==='ready'?'selected':'research-card'}" data-village="${v.id}"><span class="vicon">${v.icon}</span><small>${v.kicker}</small><h3>${v.name}</h3><p>${v.status==='ready'?`${MISSIONS.length} aventures actuellement structurées.`:`${v.research?.length||0} référence${(v.research?.length||0)>1?'s':''} réelle${(v.research?.length||0)>1?'s':''} déjà documentée${(v.research?.length||0)>1?'s':''}.`}</p><span class="availability ${v.status==='ready'?'ready':''}">${v.status==='ready'?'Disponible':'Bientôt • voir la recherche'}</span></button>`).join('')}</div></section>
  <section id="settings" class="section-block"><div class="section-head"><div><div class="eyebrow">ÉTAPE 2</div><h2>Prépare ton expérience</h2></div><p class="small">La difficulté des énigmes s’adapte au public. La difficulté affichée sur les aventures est désormais la difficulté physique du terrain.</p></div><div class="setting-grid"><div class="card"><h3>Public</h3><div class="toggle big-toggle"><button data-public="enfant">🧒 Enfant</button><button data-public="ado">🧑 Ado</button><button data-public="adulte">🧑‍🦱 Adulte</button></div><p class="small" id="publicHelp"></p></div><div class="card team-card"><h3>Équipe locale</h3><label>Nom de l’équipe</label><input class="input" id="teamName" value="${escapeHtml(state.team.name)}" placeholder="Ex. Les Albères"><label>Nombre de joueurs</label><input class="input" id="teamPlayers" type="number" min="1" max="30" value="${state.team.players}"><label>Prénoms (facultatif)</label><input class="input" id="teamNames" value="${escapeHtml(state.team.names)}" placeholder="Fafa, Julie, …"><button class="btn secondary" id="saveTeam">Enregistrer l’équipe</button></div></div><div class="card accessibility-card"><details><summary>♿ Accessibilité & confort</summary><div class="a11y-grid"><label><input type="checkbox" id="largeText" ${state.settings.a11y.largeText?'checked':''}> Texte agrandi</label><label><input type="checkbox" id="highContrast" ${state.settings.a11y.highContrast?'checked':''}> Contraste renforcé</label><label><input type="checkbox" id="reduceMotion" ${state.settings.a11y.reduceMotion?'checked':''}> Réduire les animations</label><label><input type="checkbox" id="autoSpeak" ${state.settings.a11y.autoSpeak?'checked':''}> Lecture audio automatique des découvertes</label></div></details></div></section>
  <section id="launch" class="section-block"><div class="section-head"><div><div class="eyebrow">ÉTAPE 3</div><h2>Choisis ton aventure à Banyuls</h2></div><p class="small">Le niveau physique tient compte de l’effort, de la technicité et du risque. Une donnée non mesurée est affichée comme telle.</p></div><div class="route-filter"><button data-filter="all">Tous</button><button data-filter="facile">🟢 Facile</button><button data-filter="intermediaire">🔵 Intermédiaire</button><button data-filter="difficile">⚫ Difficile</button></div><div class="mission-grid">${filtered.map(m=>missionCard(m)).join('')||'<div class="card">Aucune mission dans ce filtre pour ton code.</div>'}</div><div class="card method-card"><h3>Comment lire le niveau ?</h3><p><b>Effort</b> = charge physique • <b>Technicité</b> = obstacles/terrain • <b>Risque</b> = conséquences possibles d’une chute ou glissade. Cette logique reprend les trois axes utilisés par la FFRandonnée ; la cotation Explor’Action reste une aide et ne remplace pas l’évaluation personnelle du terrain et de la météo.</p></div></section>
  <footer class="app-footer"><span>Explor’Action V${VERSION}</span><a href="privacy.html">Confidentialité</a><a href="terrain.html">Sécurité terrain</a></footer></main>`;
  updateExpiry();timer=setInterval(updateExpiry,1000);
  $('#adminTop').onclick=adminLogin;$('#startHome').onclick=()=>$('#territories').scrollIntoView({behavior:'smooth'});$('#scores').onclick=renderScores;$('#audio').onclick=()=>{state.settings.sound=!state.settings.sound;save();renderHome()};$('#mapAll').onclick=renderTerritoryMap;$('#guide').onclick=renderGuide;$('#installApp').onclick=installApplication;
  $$('[data-go]').forEach(b=>b.onclick=()=>$('#'+b.dataset.go)?.scrollIntoView({behavior:'smooth'}));
  $$('[data-village]').forEach(b=>b.onclick=()=>{const id=b.dataset.village;if(id==='banyuls')$('#launch').scrollIntoView({behavior:'smooth'});else renderTerritoryResearch(id)});
  $$('[data-public]').forEach(b=>b.onclick=()=>{state.settings.public=b.dataset.public;save();refreshSettings()});
  $$('[data-filter]').forEach(b=>b.onclick=()=>{state.settings.routeFilter=b.dataset.filter;save();renderHome()});
  $$('[data-mid]').forEach(b=>b.onclick=()=>renderPreflight(b.dataset.mid));
  $('#saveTeam').onclick=saveTeamFromForm;
  ['largeText','highContrast','reduceMotion','autoSpeak'].forEach(id=>$('#'+id).onchange=()=>{const key={largeText:'largeText',highContrast:'highContrast',reduceMotion:'reduceMotion',autoSpeak:'autoSpeak'}[id];state.settings.a11y[key]=$('#'+id).checked;save();applyAccessibility()});
  refreshSettings();
}
function saveTeamFromForm(){state.team.name=$('#teamName').value.trim();state.team.players=Math.max(1,Math.min(30,+$('#teamPlayers').value||1));state.team.names=$('#teamNames').value.trim();save();toast('Équipe enregistrée')}
function missionCard(m){const p=prog(m),r=m.route,progress=pct(m,p);const distLabel=r.distanceLabel||routeMetric(r.distanceKm,' km');return `<button class="mission-select physical-card ${routeLevelClass(r.level)}" data-mid="${m.id}"><span>${m.icon}</span><div><div class="mission-kickers"><small>${m.tag}</small><b class="difficulty-chip ${routeLevelClass(r.level)}">${r.levelLabel}</b></div><h3>${m.title}</h3><p>${m.story}</p><div class="route-stats"><span>📍 ${m.steps.length} étapes</span><span>🚶 ${distLabel}</span><span>↗ ${routeMetric(r.ascentM,' m D+')}</span><span>⏱ ${r.walkTime}</span></div><div class="etr"><span>E ${r.effort==null?'—':r.effort+'/5'} <small>${etrLabel(r.effort)}</small></span><span>T ${r.technical==null?'—':r.technical+'/5'} <small>${etrLabel(r.technical)}</small></span><span>R ${r.risk==null?'—':r.risk+'/5'} <small>${etrLabel(r.risk)}</small></span></div><p class="validation-chip">⚠️ Cotation et GPS à confirmer en reconnaissance terrain</p><p class="metric-note">${r.note}</p><div class="progress-mini"><i style="width:${progress}%"></i></div><small>${progress}% terminé • aventure ≈ ${r.gameTime}</small></div></button>`}
function refreshSettings(){$$('[data-public]').forEach(b=>b.classList.toggle('active',b.dataset.public===state.settings.public));$$('[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter===state.settings.routeFilter));const ph=$('#publicHelp');if(ph)ph.textContent={enfant:'Consignes plus guidées, première lettre et pénalités réduites.',ado:'Équilibre entre autonomie, observation et jeu en équipe.',adulte:'Observation plus autonome et contexte patrimonial complet.'}[state.settings.public]}
function updateExpiry(){if(state.organizerTest){const el=$('#expiry');if(el)el.textContent='Mode test';return}if(!accessValid()){clearInterval(timer);renderAccess();return}const el=$('#expiry');if(el){const ms=state.access.exp-Date.now();el.textContent=`Accès : ${ms>86400000?Math.ceil(ms/86400000)+' j':Math.ceil(ms/3600000)+' h'}`}}

function renderTerritoryResearch(id){const v=TERRITORIES.find(x=>x.id===id);if(!v)return renderHome();stopLive();app.innerHTML=`<main class="shell"><header class="topbar">${logoHTML()}<button class="btn secondary" id="back">← Accueil</button></header><section class="card hero"><div><span class="pill">${v.status==='ready'?'Disponible':'Bientôt'}</span><h1>${v.icon} ${v.name}</h1><p class="subtitle">${v.kicker}</p><p>${v.status==='ready'?'Banyuls est le territoire actuellement jouable.':'Ces références servent à concevoir les futurs parcours. Elles ne sont pas transformées en jeu tant que les lieux, enchaînements et coordonnées de géofencing n’ont pas été reconnus physiquement.'}</p></div><img class="hero-avatar" src="${ASSETS.adventure}" alt="FAFA"></section><section class="card" style="margin-top:14px"><h2>Références terrain déjà vérifiées</h2>${v.research?.length?v.research.map(r=>`<article class="research-route"><b class="difficulty-chip ${routeLevelClass(r.level)}">${r.level==='intermediaire'?'Intermédiaire':r.level==='difficile'?'Difficile':'Facile'}</b><h3>${r.name}</h3><p>${r.distanceKm!=null?`${r.distanceKm} km • `:''}${r.ascentM!=null?`+${r.ascentM} m D+ • `:''}${r.time}</p><a href="${r.source}" target="_blank" rel="noopener">Source officielle ↗</a></article>`).join(''):'<p>Aucune randonnée de référence n’est encore retenue : il faut d’abord documenter le territoire sans forcer un parcours artificiel.</p>'}</section></main>`;$('#back').onclick=renderHome}
function renderAllTerritoryResearch(){app.innerHTML=`<main class="shell"><button class="btn secondary back" id="back">← Admin</button><h1>Recherche des 11 territoires</h1><p class="subtitle">Catalogue documentaire uniquement. Aucun point GPS joueur n’est créé à partir de ces références sans reconnaissance terrain.</p>${TERRITORIES.map(v=>`<section class="card audit-card"><h2>${v.icon} ${v.name}</h2>${v.research?.length?v.research.map(r=>`<p><b>${r.name}</b> — ${r.distanceKm??'?'} km • +${r.ascentM??'?'} m • ${r.time}<br><a href="${r.source}" target="_blank" rel="noopener">Source ↗</a></p>`).join(''):'<p class="small">Recherche à poursuivre.</p>'}</section>`).join('')}</main>`;$('#back').onclick=renderAdmin}

async function renderPreflight(mid){
  stopLive();clearInterval(timer);const m=MISSIONS.find(x=>x.id===mid);if(!m||!allowed(m))return toast('Mission non autorisée');currentMission=m;const p=prog(m),r=m.route;
  app.innerHTML=`<main class="shell">${state.organizerTest?'<div class="test-banner">🧪 MODE TEST ORGANISATEUR</div>':''}<header class="topbar">${logoHTML()}<button class="btn secondary" id="back">← Missions</button></header><section class="card hero"><div><div class="mission-kickers"><span class="pill">${m.icon} ${m.tag}</span><b class="difficulty-chip ${routeLevelClass(r.level)}">${r.levelLabel}</b></div><h1>${m.title}</h1><p class="subtitle">${m.story}</p><div class="route-stats preflight-stats"><span>📍 ${m.steps.length} étapes</span><span>🚶 ${r.distanceLabel||routeMetric(r.distanceKm,' km')}</span><span>↗ ${routeMetric(r.ascentM,' m D+')}</span><span>↘ ${routeMetric(r.descentM,' m D-')}</span><span>🏔 ${routeMetric(r.altMaxM,' m max')}</span><span>⏱ ${r.walkTime}</span></div><div class="etr"><span>E ${r.effort==null?'—':r.effort+'/5'} • ${etrLabel(r.effort)}</span><span>T ${r.technical==null?'—':r.technical+'/5'} • ${etrLabel(r.technical)}</span><span>R ${r.risk==null?'—':r.risk+'/5'} • ${etrLabel(r.risk)}</span></div><p class="warning"><b>Validation terrain obligatoire.</b> ${r.note}</p></div><img class="hero-avatar" src="${ASSETS[MISSION_GUIDE[m.id]||'adventure']}" alt="FAFA"></section><section class="preflight-grid"><div class="card"><h2>Avant de partir</h2><div class="checklist"><div id="chkOnline">⏳ Connexion</div><div id="chkOffline">⏳ PWA / cache</div><div id="chkGps">⏳ GPS</div><div id="chkBattery">⏳ Batterie</div></div><button class="btn secondary" id="runChecks">Relancer les vérifications</button></div><div class="card"><h2>Terrain & sécurité</h2><p>🥾 ${r.surface}</p><p>♿ ${r.accessibility}</p><p class="warning">${m.safety}</p><a class="btn danger" href="${FIRE_RISK_URL}" target="_blank" rel="noopener">🔥 Vérifier le risque incendie du jour ↗</a><details><summary>Accès / saisonnalité des étapes</summary>${m.steps.map((s,i)=>`<p class="small"><b>${i+1}. ${s.name}</b><br>${s.access}<br>${s.season}</p>`).join('')}</details></div></section>${guideHTML('guard','Le terrain passe avant le jeu','Si une fermeture, une déviation ou la météo rend le parcours dangereux, ne cherche pas à atteindre la balise. Le mode SOS existe pour la sécurité, pas pour gagner du temps.')}<div class="card preflight-launch"><h2>${p.started?'Reprendre la mission':'Prêt à partir ?'}</h2><p>Équipe : <b>${escapeHtml(state.team.name||'Sans nom')}</b> • ${state.team.players} joueur${state.team.players>1?'s':''} • Public : <b>${state.settings.public}</b></p><p>Score : <b>${p.score}</b> • progression : <b>${p.done.length}/${m.steps.length}</b> • durée aventure : <b>${r.gameTime}</b></p><button class="btn" id="goMission">${p.started?'▶️ Reprendre':'🚀 Démarrer la mission'}</button></div></main>`;
  $('#back').onclick=renderHome;$('#runChecks').onclick=runPreflightChecks;$('#goMission').onclick=()=>{if(!p.started){p.elapsedMs=0;p.done=[];p.reached=[];p.skipped=[];p.tokens=[];p.score=0;p.hints=0;p.errors=0;p.finalDone=false;currentStep=0}else currentStep=Math.min(p.done.length,m.steps.length-1);startClock(p);save();renderMission()};runPreflightChecks();
}
async function runPreflightChecks(){const on=$('#chkOnline'),off=$('#chkOffline'),gps=$('#chkGps'),bat=$('#chkBattery');if(on)on.textContent=navigator.onLine?'✅ Connexion disponible':'⚠️ Hors connexion';if(off)off.textContent=navigator.serviceWorker?.controller?'✅ PWA / cache actif':'⚠️ Cache pas encore contrôlé (recharge après installation)';if(bat){try{const b=await navigator.getBattery?.();bat.textContent=b?`${b.level>.35?'✅':'⚠️'} Batterie ${Math.round(b.level*100)}%${b.charging?' • en charge':''}`:'ℹ️ Batterie : information non disponible'}catch{bat.textContent='ℹ️ Batterie : information non disponible'}}if(gps){if(!navigator.geolocation)gps.textContent='❌ GPS indisponible';else navigator.geolocation.getCurrentPosition(p=>gps.textContent=`✅ GPS prêt • précision ±${Math.round(p.coords.accuracy)} m`,e=>gps.textContent=`⚠️ GPS : ${e.message}`,{enableHighAccuracy:true,timeout:10000,maximumAge:10000})}}

function renderMission(tab='mission'){
  stopLive();clearInterval(timer);const m=currentMission;if(!m)return renderHome();const p=prog(m);if(!allowed(m))return renderHome();
  if(p.paused){app.innerHTML=`<main class="shell"><header class="topbar">${logoHTML()}<button class="btn secondary" id="quit">← Accueil</button></header><section class="card hero"><img class="hero-avatar" src="${ASSETS.calm}" alt="FAFA"><div><span class="pill">⏸ Mission en pause</span><h1>${m.title}</h1><p class="subtitle">Le chronomètre est arrêté. Ta progression est sauvegardée.</p><p>Temps joué : <b>${formatMs(liveElapsed(p))}</b> • ${p.done.length}/${m.steps.length} étapes</p><button class="btn" id="resume">▶️ Reprendre</button></div></section></main>`;$('#quit').onclick=renderHome;$('#resume').onclick=()=>{resumeClock(p);renderMission()};return}
  app.innerHTML=`<main class="shell mission-shell">${state.organizerTest?'<div class="test-banner compact">🧪 TEST</div>':''}<header class="mission-head">${logoHTML(false,'mission-logo')}<div class="mission-head-copy"><small>${m.icon} ${m.title}</small><div class="mission-progress"><i style="width:${pct(m,p)}%"></i></div><b>${p.done.length}/${m.steps.length} • <span id="clock">${formatMs(liveElapsed(p))}</span></b></div><button class="icon-btn" id="pause">⏸</button><button class="icon-btn" id="home">⌂</button></header><nav class="mission-nav"><button data-tab="mission">🎯 Mission</button><button data-tab="map">🗺 Carte</button><button data-tab="bag">🎒 Sac</button><button data-tab="score">🏆 Score</button><button data-tab="help">🆘 Aide</button></nav><section id="view"></section></main>`;
  $('#pause').onclick=()=>{pauseClock(p);renderMission()};$('#home').onclick=()=>{pauseClock(p);renderHome()};$$('[data-tab]').forEach(b=>b.onclick=()=>renderTab(b.dataset.tab));renderTab(tab);timer=setInterval(()=>{const c=$('#clock');if(c)c.textContent=formatMs(liveElapsed(p))},1000)
}
function renderTab(tab){const m=currentMission,p=prog(m),v=$('#view');if(!v)return;$$('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));if(tab==='mission'){if(p.done.length>=m.steps.length)return renderFinal(v,m,p);currentStep=Math.min(currentStep,p.done.length,m.steps.length-1);const s=m.steps[currentStep],reached=state.organizerTest||p.reached.includes(currentStep)||p.skipped.includes(currentStep)||p.done.includes(currentStep),rules=scoreRules(),rad=effectiveRadius(s);v.innerHTML=`<section class="card step-card"><div class="step-top"><div><span class="pill">Étape ${currentStep+1}/${m.steps.length}</span><h2>${s.name}</h2><p class="small">${publicTip()}</p></div><div class="step-score">${p.score}<small>pts</small></div></div><div class="gps-gate ${reached?'open':''}"><h3>${state.organizerTest?'🧪 Zone simulée':reached?'✅ Zone validée':'📍 Rejoins la zone'}</h3><p>${reached?'L’épreuve est déverrouillée.':`Approche-toi du lieu. Tolérance actuelle : environ ${rad} m, ajustée au public et à la précision GPS.`}</p><div class="row"><button class="btn secondary" id="gpsCheck">${state.organizerTest?'Valider en test':'Vérifier ma position'}</button><button class="btn secondary" id="compass">🧭 Boussole</button>${reached?`<a class="btn secondary" href="https://www.openstreetmap.org/?mlat=${s.lat}&mlon=${s.lng}#map=18/${s.lat}/${s.lng}" target="_blank" rel="noopener">Carte OSM ↗</a>`:''}</div><div id="navInfo" class="nav-info"></div>${!reached?`<button class="sos-link" id="sos">⚠️ Lieu fermé / inaccessible</button>`:''}</div><div id="challengeZone">${reached?challengeHTML(s,p,rules):'<div class="locked-challenge">🔒 L’énigme apparaît lorsque la zone est validée.</div>'}</div></section>`;$('#gpsCheck').onclick=()=>state.organizerTest?unlockTest(currentStep):checkGeoAndUnlock(s,currentStep);$('#compass').onclick=()=>startCompass(s);if($('#sos'))$('#sos').onclick=()=>{if(confirm(`Débloquer cette étape en mode SOS ? Pénalité -${rules.skip} points et assistance enregistrée.`)){if(!p.skipped.includes(currentStep))p.skipped.push(currentStep);if(!p.reached.includes(currentStep))p.reached.push(currentStep);p.score=Math.max(0,p.score-rules.skip);save();renderTab('mission')}};if(reached)bindChallenge(s,p,rules)}else if(tab==='map')renderMapTab(v,m,p);else if(tab==='bag')renderBag(v,m,p);else if(tab==='score')renderScoreTab(v,m,p);else renderHelp(v,m,p)}
function unlockTest(i){const p=prog(currentMission);if(!p.reached.includes(i))p.reached.push(i);save();renderTab('mission')}
function challengeHTML(s,p,rules){const useChoices=!!s.choices;return `<div class="challenge-block"><div class="challenge-type">${iconForType(s.type)} ${labelForType(s.type)}</div><h3>Épreuve</h3><p class="challenge">${questionText(s)}</p>${useChoices?`<div class="toggle choice-grid">${s.choices.map(c=>`<button class="btn secondary choice" data-v="${escapeHtml(c)}">${c}</button>`).join('')}</div>`:'<input class="input" id="answer" placeholder="Ta réponse…">'}<div class="row" style="margin-top:12px"><button class="btn" id="validate">Valider (+${rules.success})</button><button class="btn gold" id="hint">Indice (-${rules.hint})</button></div><p id="feedback" class="feedback"></p><div id="hintbox"></div><div id="discovery"></div></div>`}
function iconForType(t){return {cipher:'🔐',choice:'🔘',riddle:'🧩',sequence:'🔢',observation:'👀',logic:'🧠',multi:'🔗',finalpiece:'🗝️',word:'🔤'}[t]||'🧩'}
function labelForType(t){return {cipher:'Code',choice:'Choix',riddle:'Énigme',sequence:'Ordre',observation:'Observation',logic:'Logique',multi:'Association',finalpiece:'Fragment final',word:'Jeu de mots'}[t]||'Défi'}
function bindChallenge(s,p,rules){let selected='';$$('.choice').forEach(b=>b.onclick=()=>{selected=b.dataset.v;$$('.choice').forEach(x=>x.classList.remove('active'));b.classList.add('active')});$('#hint').onclick=()=>{if($('#hintbox').innerHTML)return;p.hints++;p.score=Math.max(0,p.score-rules.hint);save();const txt=state.settings.public==='enfant'?`${s.hint} Première lettre : ${firstLetter(s)}.`:s.hint;$('#hintbox').innerHTML=guideHTML('think','Un coup de pouce',txt);haptic(20)};$('#validate').onclick=()=>{const a=s.choices?selected:($('#answer')?.value||'');if(s.answers.some(x=>norm(x)===norm(a))){if(!p.done.includes(currentStep)){p.done.push(currentStep);p.score+=rules.success;p.tokens.push(s.token);save()}chime(true);haptic([40,60,80]);$('#feedback').className='feedback good';$('#feedback').textContent=`Réussi ! Fragment : ${s.token}`;$('#validate').disabled=true;$('#hint').disabled=true;$('#discovery').innerHTML=discoveryHTML(s,currentStep);bindDiscovery(s,currentStep)}else{p.errors++;p.score=Math.max(0,p.score-rules.error);save();chime(false);haptic([80,40,80]);$('#feedback').className='feedback bad';$('#feedback').textContent=`Pas encore. -${rules.error} pts. Observe de nouveau le lieu.`}}}
function discoveryHTML(s,i){return `<div class="discovery"><div class="discovery-title"><span>💡 Le savais-tu ?</span><button class="speak-btn" id="speakFact">🔊</button></div><div class="discovery-body"><img src="${ASSETS.welcome}" alt="FAFA explique"><p>${factText(s)}</p></div>${s.photoBonus?`<div class="photo-bonus"><b>📸 Bonus souvenir (facultatif)</b><p class="small">La photo est compressée puis enregistrée dans IndexedDB sur cet appareil. Elle n’est pas envoyée sur un serveur.</p><input id="photoInput" type="file" accept="image/*" capture="environment"><div id="photoStatus"></div></div>`:''}<div class="row"><a class="btn secondary" href="${s.source}" target="_blank" rel="noopener">Source ↗</a><button class="btn" id="continue">Continuer →</button></div></div>`}
function bindDiscovery(s,i){$('#speakFact').onclick=()=>speak(factText(s));if(state.settings.a11y.autoSpeak)speak(factText(s));if($('#photoInput'))$('#photoInput').onchange=e=>savePhoto(currentMission.id,i,e.target.files?.[0]);$('#continue').onclick=()=>{currentStep=Math.min(prog(currentMission).done.length,currentMission.steps.length-1);renderTab('mission')}}
function checkGeoAndUnlock(s,i){const el=$('#navInfo');if(!navigator.geolocation){el.textContent='GPS indisponible';return}el.textContent='Recherche GPS…';navigator.geolocation.getCurrentPosition(g=>{const p=prog(currentMission),m=Math.round(dist(g.coords.latitude,g.coords.longitude,s.lat,s.lng)*1000),rad=effectiveRadius(s),tol=rad+Math.min(Math.max(g.coords.accuracy||0,0),80),b=bearing(g.coords.latitude,g.coords.longitude,s.lat,s.lng);currentBearing=b;el.innerHTML=`Distance ≈ <b>${m} m</b> • précision ±${Math.round(g.coords.accuracy)} m • cap <b>${Math.round(b)}° ${cardinal(b)}</b>`;if(m<=tol){if(!p.reached.includes(i))p.reached.push(i);save();chime(true);haptic([40,40,40]);toast('Zone découverte !');renderTab('mission')}else toast(`Encore environ ${m} m`)},e=>el.textContent='GPS : '+e.message,{enableHighAccuracy:true,timeout:12000,maximumAge:5000})}
async function startCompass(s){const el=$('#navInfo');if(!navigator.geolocation)return toast('GPS indisponible');try{if(typeof DeviceOrientationEvent!=='undefined'&&typeof DeviceOrientationEvent.requestPermission==='function'){const perm=await DeviceOrientationEvent.requestPermission();if(perm!=='granted')throw new Error('Boussole refusée')}}catch{}window.addEventListener('deviceorientationabsolute',onOrientation);window.addEventListener('deviceorientation',onOrientation);geoWatch=navigator.geolocation.watchPosition(g=>{const m=Math.round(dist(g.coords.latitude,g.coords.longitude,s.lat,s.lng)*1000),b=bearing(g.coords.latitude,g.coords.longitude,s.lat,s.lng);currentBearing=b;const rel=heading==null?b:(b-heading+360)%360;el.innerHTML=`<div class="compass-wrap"><div class="compass-arrow" style="transform:rotate(${rel}deg)">➤</div><div><b>${m} m</b><br>Cap ${Math.round(b)}° ${cardinal(b)}${heading==null?'<br><small>Orientation téléphone non disponible : flèche = nord géographique.</small>':''}</div></div>`},e=>el.textContent='Boussole/GPS : '+e.message,{enableHighAccuracy:true,maximumAge:2000,timeout:10000})}
function onOrientation(e){heading=e.webkitCompassHeading!=null?e.webkitCompassHeading:(e.alpha!=null?(360-e.alpha)%360:null)}

function visibleIndices(m,p){if(p.finalDone)return m.steps.map((_,i)=>i);const set=new Set(p.done);if(p.done.length<m.steps.length)set.add(p.done.length);return [...set].sort((a,b)=>a-b)}
function renderMapTab(v,m,p){const vis=visibleIndices(m,p);v.innerHTML=`<section class="card"><div class="section-head"><div><h2>Carte progressive</h2><p class="small">Anti-spoiler : seules les étapes déjà découvertes et la prochaine étape sont visibles. Le parcours complet apparaît après la réussite finale.</p></div><span class="pill">${pct(m,p)}%</span></div><div id="onlineMap" class="leaflet-map"><div class="map-loading">Carte en ligne si disponible…</div></div>${mapHTML(m,p,vis)}<div class="map-list">${m.steps.map((s,i)=>vis.includes(i)?`<button class="map-row ${p.done.includes(i)?'done':'current'}" data-step="${i}"><span>${p.done.includes(i)?'✓':i+1}</span><div><b>${s.name}</b><small>${p.done.includes(i)?'Terminée':'Prochaine étape'}</small></div></button>`:`<div class="map-row lock"><span>🔒</span><div><b>Étape à découvrir</b><small>Nom masqué</small></div></div>`).join('')}</div></section>`;setTimeout(()=>{placeMap(m,p,vis);initLeafletMap(m,p,vis)},0);$$('[data-step]').forEach(b=>b.onclick=()=>{const i=+b.dataset.step;if(vis.includes(i)){currentStep=i;renderTab('mission')}})}
function mapHTML(m,p,vis){return `<div class="map schematic-map" id="map"><div class="sea"></div><svg id="routeSvg" class="route-svg" viewBox="0 0 100 100" preserveAspectRatio="none"><polyline id="routeLine" points="" /></svg>${vis.map(i=>`<button class="marker ${p.done.includes(i)?'done':'current'}" data-mi="${i}" title="${m.steps[i].name}"><span>${i+1}</span></button>`).join('')}<div class="player hidden" id="player"></div></div><div class="row" style="margin-top:12px"><button class="btn secondary" id="mapgps">📍 Ma position</button><span class="small">Schéma de secours hors connexion</span></div>`}
function placeMap(m,p,vis){const shown=vis.map(i=>m.steps[i]);if(!shown.length)return;const lats=shown.map(x=>x.lat),lngs=shown.map(x=>x.lng),minA=Math.min(...lats),maxA=Math.max(...lats),minO=Math.min(...lngs),maxO=Math.max(...lngs),pts=[];$$('.marker').forEach(x=>{const i=+x.dataset.mi,s=m.steps[i],px=8+84*(s.lng-minO)/(maxO-minO||1),py=8+80*(maxA-s.lat)/(maxA-minA||1);pts.push(`${px},${py}`);x.style.left=`calc(${px}% - 17px)`;x.style.top=`calc(${py}% - 17px)`});const line=$('#routeLine');if(line)line.setAttribute('points',pts.join(' '));$('#mapgps').onclick=()=>navigator.geolocation&&navigator.geolocation.getCurrentPosition(g=>{const px=8+84*(g.coords.longitude-minO)/(maxO-minO||1),py=8+80*(maxA-g.coords.latitude)/(maxA-minA||1),pl=$('#player');pl.classList.remove('hidden');pl.style.left=`calc(${Math.max(2,Math.min(96,px))}% - 10px)`;pl.style.top=`calc(${Math.max(2,Math.min(96,py))}% - 10px)`;toast(`Précision GPS ±${Math.round(g.coords.accuracy)} m`)},()=>toast('GPS indisponible'))}
async function loadLeaflet(){if(window.L)return true;if(!navigator.onLine)return false;return new Promise(resolve=>{const css=document.createElement('link');css.rel='stylesheet';css.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';document.head.appendChild(css);const s=document.createElement('script');s.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';s.onload=()=>resolve(true);s.onerror=()=>resolve(false);document.head.appendChild(s)})}
async function initLeafletMap(m,p,vis){const el=$('#onlineMap');if(!el)return;const ok=await loadLeaflet();if(!ok){el.innerHTML='<div class="map-loading">Hors connexion : utilise le schéma de secours.</div>';return}const points=vis.map(i=>m.steps[i]);if(!points.length)return;leafletMap=L.map(el,{zoomControl:true});L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(leafletMap);const bounds=[];points.forEach((s,idx)=>{const marker=L.marker([s.lat,s.lng]).addTo(leafletMap).bindPopup(`${vis[idx]+1}. ${escapeHtml(s.name)}`);bounds.push([s.lat,s.lng])});if(bounds.length===1)leafletMap.setView(bounds[0],16);else leafletMap.fitBounds(bounds,{padding:[25,25]});if(navigator.geolocation)navigator.geolocation.getCurrentPosition(g=>{leafletPlayer=L.circleMarker([g.coords.latitude,g.coords.longitude],{radius:8}).addTo(leafletMap).bindPopup('Ma position')},()=>{},{enableHighAccuracy:true,timeout:8000})}

async function renderBag(v,m,p){v.innerHTML=`<section class="card"><h2>🎒 Sac d’exploration</h2><h3>Fragments</h3><div class="inventory">${p.tokens.length?p.tokens.map((t,i)=>`<span class="token">${i+1}. <b>${t}</b></span>`).join(''):'<span class="small">Aucun fragment.</span>'}</div></section><section class="card" style="margin-top:14px"><h3>📖 Journal « Le savais-tu ? »</h3>${p.done.length?p.done.map(i=>`<details><summary>${m.steps[i].name}</summary><p>${factText(m.steps[i])}</p><button class="speak-btn journal-speak" data-i="${i}">🔊 Écouter</button></details>`).join(''):'<p class="small">Résous une étape pour débloquer son histoire.</p>'}</section><section class="card" style="margin-top:14px"><h3>📸 Souvenirs locaux</h3><div class="photo-grid" id="photos"><p class="small">Chargement…</p></div></section>`;$$('.journal-speak').forEach(b=>b.onclick=()=>speak(factText(m.steps[+b.dataset.i])));try{const photos=await photoList(m.id),box=$('#photos');if(!box)return;if(!photos.length)box.innerHTML='<p class="small">Aucune photo enregistrée.</p>';else box.innerHTML=photos.map(x=>{const u=URL.createObjectURL(x.blob);photoObjectUrls.push(u);return `<figure><img src="${u}" alt="Souvenir étape ${x.step+1}"><figcaption>${m.steps[x.step]?.name||`Étape ${x.step+1}`}</figcaption></figure>`}).join('')}catch{const box=$('#photos');if(box)box.innerHTML='<p class="small">Stockage photo indisponible.</p>'}}
function renderScoreTab(v,m,p){const r=scoreRules(),badges=getBadges(m,p);v.innerHTML=`<section class="card score-card"><div class="score-guide"><img src="${ASSETS.adventure}" alt="FAFA"><div><h2>Mes scores</h2><p class="subtitle">Résultat local de l’équipe ${escapeHtml(state.team.name||'sans nom')}. Aucun faux classement en ligne.</p></div></div><div class="stats"><div class="stat"><b>${p.score}</b><small>points</small></div><div class="stat"><b>${formatMs(liveElapsed(p))}</b><small>temps joué</small></div><div class="stat"><b>${p.errors}</b><small>erreurs</small></div><div class="stat"><b>${p.hints}</b><small>indices</small></div><div class="stat"><b>${p.skipped.length}</b><small>SOS</small></div></div><h3>Progression</h3><div class="big-progress"><i style="width:${pct(m,p)}%"></i></div><p>${pct(m,p)}% • ${p.done.length}/${m.steps.length} étapes</p><h3>Badges</h3><div class="badges">${badges.map(x=>`<span class="badge">${x}</span>`).join('')}</div><p class="small">Barème public ${state.settings.public} : +${r.success}/étape, -${r.error}/erreur, -${r.hint}/indice, -${r.skip}/SOS, +${r.final} final.</p></section>`}
function renderHelp(v,m,p){v.innerHTML=`<section class="card"><h2>🆘 Aide terrain</h2>${guideHTML('guard','Une aventure, jamais un risque','Si le GPS est imprécis, attends dans un espace sûr. Si le site est fermé, dévié ou dangereux, utilise SOS et respecte les consignes locales.')}<div class="help-grid"><div><h3>GPS</h3><button class="btn secondary" id="testGps">Tester mon GPS</button><p id="gpsRes" class="small"></p></div><div><h3>Audio</h3><button class="btn secondary" id="sound">${state.settings.sound?'🔊 Activé':'🔇 Coupé'}</button></div><div><h3>Hors connexion</h3><p class="small">${navigator.serviceWorker?.controller?'✅ Application mise en cache. Les énigmes et le schéma de secours restent accessibles.':'⚠️ Recharge l’application une fois en ligne pour finaliser le cache.'}</p></div></div><a class="btn danger" href="${FIRE_RISK_URL}" target="_blank" rel="noopener">🔥 Risque incendie du jour ↗</a><details><summary>Règles de sécurité</summary><p>${m.safety}</p></details><details><summary>Source de l’étape actuelle</summary><p><a href="${m.steps[currentStep]?.source||m.sourceSummary}" target="_blank" rel="noopener">Ouvrir la source ↗</a></p></details></section>`;$('#testGps').onclick=()=>navigator.geolocation?navigator.geolocation.getCurrentPosition(g=>$('#gpsRes').textContent=`GPS OK • précision ±${Math.round(g.coords.accuracy)} m`,e=>$('#gpsRes').textContent=e.message,{enableHighAccuracy:true,timeout:10000}):$('#gpsRes').textContent='GPS indisponible';$('#sound').onclick=()=>{state.settings.sound=!state.settings.sound;save();renderTab('help')}}
function getBadges(m,p){const n=m.steps.length,b=[];if(p.done.length>=1)b.push('🧭 Premier pas');if(p.done.length>=Math.ceil(n/2))b.push('🔎 Œil d’explorateur');if(p.done.length>=n)b.push('🏁 Parcours complet');if(p.hints===0&&p.done.length>=Math.ceil(n/2))b.push('🧠 Sans indice');if(p.errors===0&&p.done.length>=Math.ceil(n/2))b.push('🎯 Précision');if(p.skipped.length===0&&p.done.length>=n)b.push('📍 100% terrain');return b.length?b:['🔒 Continue pour débloquer des badges']}
function rank(m,p){const max=missionMaxScore(m),ratio=max?Math.min(1,p.score/max):0;return ratio>=.9?'Gardien du territoire':ratio>=.75?'Expert du terrain':ratio>=.55?'Aventurier':'Explorateur'}
function renderFinal(v,m,p){const guess=p.tokens.join(' '),rules=scoreRules();v.innerHTML=`<section class="card hero success-screen final-screen"><img class="final-avatar" src="${ASSETS.point}" alt="FAFA"><div><div class="trophy">🔐</div><span class="pill">${p.tokens.length} fragments</span><h2>Grand final</h2><p class="subtitle">Fragments : <b>${guess}</b></p><p>Assemble les fragments utiles pour retrouver le mot-clé de la mission.</p><input class="input" id="finalanswer" placeholder="Mot-clé final"><button class="btn" id="finalbtn">Ouvrir le coffre (+${rules.final})</button><p class="feedback" id="finalfb"></p></div></section>`;$('#finalbtn').onclick=()=>{if(norm($('#finalanswer').value)===norm(m.final)){if(!p.finalDone){p.finalDone=true;p.score+=rules.final;pauseClock(p);save()}chime(true);haptic([100,50,100,50,180]);showPremiumResult(v,m,p)}else{chime(false);$('#finalfb').className='feedback bad';$('#finalfb').textContent='Le coffre reste fermé. Relis tes fragments et ton journal.'}}}
function showPremiumResult(v,m,p){const badges=getBadges(m,p),r=rank(m,p),team=state.team.name||'Équipe Explor’Action';v.innerHTML=`<section class="card premium-result"><div class="result-head"><img src="${ASSETS.logoPremium}" alt="FAFATRAINING"><div><span class="pill">🏁 MISSION ACCOMPLIE</span><h1>${m.title}</h1><p>${escapeHtml(team)} • ${state.team.players} joueur${state.team.players>1?'s':''}</p></div></div><div class="result-grid"><div><b>${p.score}</b><small>score</small></div><div><b>${formatMs(liveElapsed(p))}</b><small>temps</small></div><div><b>${r}</b><small>rang</small></div><div><b>${p.hints}</b><small>indices</small></div><div><b>${p.errors}</b><small>erreurs</small></div><div><b>${p.skipped.length}</b><small>SOS</small></div></div><h3>Badges obtenus</h3><div class="badges">${badges.map(x=>`<span class="badge">${x}</span>`).join('')}</div><h3>Découvertes</h3><p>${m.steps.map(s=>s.name).join(' • ')}</p><div class="row result-actions"><button class="btn" id="shareResult">Partager le résultat</button><button class="btn secondary" id="diploma">Enregistrer le diplôme</button><button class="btn secondary" id="another">Autre mission</button></div>${state.organizerTest?'<p class="warning">Résultat obtenu en mode test organisateur : non officiel.</p>':''}</section>`;$('#shareResult').onclick=()=>shareResult(m,p,r);$('#diploma').onclick=()=>downloadDiploma(m,p,r);$('#another').onclick=()=>{pauseClock(p);renderHome()}}
async function shareResult(m,p,r){const text=`Explor’Action — ${m.title}\n${state.team.name||'Équipe'} • ${p.score} pts • ${formatMs(liveElapsed(p))} • ${r}`;try{if(navigator.share)await navigator.share({title:'Explor’Action',text});else{await navigator.clipboard.writeText(text);toast('Résultat copié')}}catch{}}
function downloadDiploma(m,p,r){const c=document.createElement('canvas');c.width=1600;c.height=1000;const x=c.getContext('2d');x.fillStyle='#07130d';x.fillRect(0,0,c.width,c.height);x.strokeStyle='#35e078';x.lineWidth=12;x.strokeRect(45,45,c.width-90,c.height-90);x.fillStyle='#ffffff';x.textAlign='center';x.font='bold 64px sans-serif';x.fillText('EXPLOR’ACTION',800,170);x.fillStyle='#35e078';x.font='bold 38px sans-serif';x.fillText('MISSION ACCOMPLIE',800,240);x.fillStyle='#ffffff';x.font='bold 52px sans-serif';x.fillText(m.title,800,350);x.font='38px sans-serif';x.fillText(state.team.name||'Équipe Explor’Action',800,440);x.font='30px sans-serif';x.fillText(`${p.score} points • ${formatMs(liveElapsed(p))} • ${r}`,800,520);x.fillText(`${state.team.players} joueur${state.team.players>1?'s':''} • ${new Date().toLocaleDateString('fr-FR')}`,800,590);x.fillStyle='#a9b7af';x.font='26px sans-serif';x.fillText('FAFATRAINING • aventure, terrain, patrimoine',800,790);const a=document.createElement('a');a.download=`diplome-explor-action-${m.id}.png`;a.href=c.toDataURL('image/png');a.click()}

function renderScores(){stopLive();const rows=MISSIONS.filter(allowed).map(m=>({m,p:prog(m)}));app.innerHTML=`<main class="shell"><header class="topbar">${logoHTML()}<button class="btn secondary" id="back">← Accueil</button></header><section class="card"><h1>🏆 Mes scores</h1><p class="subtitle">Résultats enregistrés uniquement sur cet appareil.</p><div class="leaderboard">${rows.map(({m,p})=>`<button class="score-row" data-mid="${m.id}"><b>${m.icon} ${m.title}</b><span>${p.done.length}/${m.steps.length} • ${p.score} pts • ${formatMs(liveElapsed(p))}</span></button>`).join('')}</div></section></main>`;$('#back').onclick=renderHome;$$('[data-mid]').forEach(b=>b.onclick=()=>renderPreflight(b.dataset.mid))}
function renderGuide(){stopLive();app.innerHTML=`<main class="shell"><header class="topbar">${logoHTML()}<button class="btn secondary" id="back">← Accueil</button></header><section class="card hero"><img class="hero-avatar" src="${ASSETS.think}" alt="FAFA"><div><span class="pill">❓ Guide FAFA</span><h1>Comment jouer ?</h1><div class="guide-steps"><p><b>1.</b> Choisis un territoire disponible puis regarde le niveau physique réel de l’aventure.</p><p><b>2.</b> Lis distance, dénivelé, temps de marche, temps avec jeu, terrain, effort, technicité et risque.</p><p><b>3.</b> Vérifie GPS, batterie, météo et risque incendie avant de partir.</p><p><b>4.</b> Rejoins la zone GPS : l’énigme se déverrouille.</p><p><b>5.</b> Observe le lieu réel, résous l’épreuve, découvre son histoire et récupère un fragment.</p><p><b>6.</b> La carte ne révèle que le chemin déjà découvert et la prochaine étape.</p><p><b>7.</b> Assemble les fragments et termine avec le bilan premium de ton équipe.</p></div><div class="row"><button class="btn" id="listen">🔊 Écouter</button><button class="btn secondary" id="gpsTest">📍 Tester GPS</button></div><p id="gtest"></p></div></section></main>`;$('#back').onclick=renderHome;$('#listen').onclick=()=>speak('Choisis une aventure adaptée à ton niveau physique. Vérifie le terrain, le GPS, la météo et le risque incendie. Rejoins la zone, observe le lieu et résous l’énigme.');$('#gpsTest').onclick=()=>navigator.geolocation?navigator.geolocation.getCurrentPosition(g=>$('#gtest').textContent=`GPS prêt, précision environ ${Math.round(g.coords.accuracy)} mètres`,e=>$('#gtest').textContent=e.message,{enableHighAccuracy:true,timeout:10000}):$('#gtest').textContent='GPS indisponible'}
function renderTerritoryMap(){stopLive();const v=TERRITORIES.find(x=>x.id==='banyuls');app.innerHTML=`<main class="shell"><header class="topbar">${logoHTML()}<button class="btn secondary" id="back">← Accueil</button></header><section class="card"><h1>🗺️ Banyuls-sur-Mer</h1><p class="subtitle">Carte de territoire sans spoiler. Les étapes détaillées restent cachées tant qu’une mission n’est pas lancée.</p><div id="territoryMap" class="leaflet-map territory-map"><div class="map-loading">Chargement de la carte…</div></div><div class="warning">Les coordonnées de jeu sont des zones de navigation et doivent encore être contrôlées sur le terrain avant diffusion publique. Cette carte ne remplace pas un itinéraire balisé.</div><h2>Références randonnée réelles</h2>${v.research.map(r=>`<article class="research-route"><b>${r.name}</b><p>${r.distanceKm} km • +${r.ascentM} m • ${r.time}</p><a href="${r.source}" target="_blank" rel="noopener">Source officielle ↗</a></article>`).join('')}</section></main>`;$('#back').onclick=renderHome;setTimeout(initTerritoryLeaflet,0)}
async function initTerritoryLeaflet(){const el=$('#territoryMap');if(!el)return;const ok=await loadLeaflet();if(!ok){el.innerHTML='<div class="map-loading">Carte en ligne indisponible.</div>';return}leafletMap=L.map(el).setView([42.483,3.13],14);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(leafletMap);L.circle([42.483,3.13],{radius:1800,fillOpacity:.08}).addTo(leafletMap).bindPopup('Zone générale de Banyuls-sur-Mer')}

async function installApplication(){if(installPrompt){installPrompt.prompt();const r=await installPrompt.userChoice;installPrompt=null;return toast(r.outcome==='accepted'?'Installation lancée':'Installation annulée')}const ios=/iphone|ipad|ipod/i.test(navigator.userAgent);toast(ios?'Sur iPhone/iPad : Partager → Sur l’écran d’accueil':'Utilise le menu du navigateur → Installer l’application / Ajouter à l’écran d’accueil')}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e});
window.addEventListener('online',()=>toast('Connexion retrouvée'));window.addEventListener('offline',()=>toast('Mode hors connexion'));
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
applyAccessibility();save();
accessValid()?renderHome():renderAccess();
